### PR TITLE
Use json instead of pickle for storage

### PR DESCRIPTION
**Pull request by SabatierBoris**

### CODE REVIEW

**Comment by paulfariello** [comment]
Thanks for this PR. Storing data in json would ease fixing things manually.

IIRC I choose pickle in the first place because it kept all the `*Proxy` objects when loading storage.
You remove this same objects when dumping json but they are not restored.
As far as I can tell, we could loose new entries when using non proxied storage.

**Comment by SabatierBoris** [comment]
Indeed, I we lost the *Proxy when it's load from storage. It should be fixed.

**Comment by paulfariello** [comment]
Thanks,

But this way what would happens if one calls ```__setitem__()``` and then ```__getitem__()``` ?
My guess is that he would get a proxied proxy, isn't it?

**Comment by SabatierBoris** [comment]
No.

When you develop the proxy method, you did it well. It check if it a dict or a list. Else it didn't modify it.

**Pull request merged**
